#include "../enemy_races/human.h"
#include "../enemy_races/dwarf.h"
#include "../enemy_races/elf.h"
#include "../enemy_races/orc.h"
#include "../enemy_races/merchant.h"
#include "../enemy_races/dragon.h"
#include "../enemy_races/halfling.h"